name = "donnimsipa"
compatibility_date = "2025-09-30"
send_metrics=false
workers_dev = false

[vars]
ENVIRONMENT = "production"

[assets]
directory = ".svelte-kit/cloudflare"

[env.production]
name = "donnimsipa"

[[routes]]
pattern = "about.donnimsipa.my.id"
custom_domain = true