<script lang="ts">
  import type { ProjectMetadata } from '$lib/types/project';
  import { onMount, tick } from 'svelte';
  import { page } from '$app/stores';

  onMount(async () => {
    // Dynamically import mermaid to avoid SSR issues
    const mermaidModule = await import('mermaid');
    const mermaid = mermaidModule.default;
    
    // Initialize mermaid
    mermaid.initialize({
      startOnLoad: false,
      theme: document.documentElement.classList.contains('dark') ? 'dark' : 'default',
      securityLevel: 'loose'
    });

    await tick();

    // Find all mermaid code blocks generated by MDSveX
    const mermaidBlocks = document.querySelectorAll('pre.language-mermaid code, code.language-mermaid');
    
    if (mermaidBlocks.length > 0) {
      mermaidBlocks.forEach((block, index) => {
        // Find the outermost container (usually <pre>)
        const container = block.parentElement?.tagName.toLowerCase() === 'pre' ? block.parentElement : block;
        
        const graphDefinition = block.textContent || '';
        
        // Create wrapper for mermaid
        const wrapper = document.createElement('div');
        wrapper.className = 'mermaid-wrapper mermaid';
        wrapper.textContent = graphDefinition;
        
        // Replace the code block with our new wrapper
        container.parentNode?.replaceChild(wrapper, container);
      });
      
      // Render the mermaid diagrams
      try {
        await mermaid.run({
          querySelector: '.mermaid'
        });
      } catch (err) {
        console.error('Mermaid rendering failed', err);
      }
    }
  });

  // MDSveX injects frontmatter as named props — use Svelte 4 export let syntax
  // (MDSveX layout components must be Svelte 4 compatible)
  export let title: string = '';
  export let description: string = '';
  export let tags: string[] = [];
  export let category: string = '';
  export let stack: string[] = [];
  export let featured: boolean = false;
  export let date: string = '';
  export let duration: string = '';
  export let role: string = '';
  export let readTime: number = 5;
  
  $: sections = $page.data.meta?.sections || {};

  const formattedDate = date
    ? new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  $: jsonLd = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: title,
    description,
    datePublished: date,
    author: { '@type': 'Person', name: 'Donni Maulana Sipa' },
    keywords: [...tags, ...stack].join(', ')
  });

  // Category color map
  const categoryColors: Record<string, string> = {
    'Backend Infrastructure': 'from-teal-500 to-cyan-500',
    'API Development': 'from-violet-500 to-purple-500',
    'System Integration': 'from-orange-500 to-amber-500',
    'Data Engineering': 'from-blue-500 to-indigo-500'
  };
  const catGradient = categoryColors[category] || 'from-primary-500 to-accent-500';
</script>

<svelte:head>
  <title>{title} — Donni Maulana Sipa</title>
  <meta name="description" content={description} />
  <meta property="og:title" content={title} />
  <meta property="og:description" content={description} />
  <meta property="og:type" content="article" />
  <meta property="article:published_time" content={date} />
  {#each tags as tag}
    <meta property="article:tag" content={tag} />
  {/each}
  <meta name="twitter:card" content="summary_large_image" />
  <!-- JSON-LD -->
  {@html `<script type="application/ld+json">${jsonLd}<\/script>`}
</svelte:head>

<div class="page-container py-8 md:py-12">
  <!-- Back navigation -->
  <div class="mb-8">
    <a
      href="/case-studies"
      class="inline-flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400 hover:text-primary-600 dark:hover:text-primary-400 transition-colors no-underline group"
    >
      <span class="i-lucide-arrow-left text-base group-hover:-translate-x-0.5 transition-transform"></span>
      {sections.case_studies || "All Case Studies"}
    </a>
  </div>

  <!-- Project Hero -->
  <header class="mb-10">
    <div class="relative overflow-hidden rounded-3xl p-7 sm:p-9 md:p-12">
      <!-- Background gradient -->
      <div class="absolute inset-0 bg-gradient-to-br from-primary-50 via-white to-accent-50 dark:from-slate-800/80 dark:via-slate-900/90 dark:to-slate-800/60 rounded-3xl"></div>
      <div class="absolute inset-0 border border-white/50 dark:border-slate-700/30 rounded-3xl"></div>
      <!-- Decorative orb -->
      <div class="absolute -top-16 -right-16 w-56 h-56 bg-primary-300/20 dark:bg-primary-500/10 rounded-full blur-3xl pointer-events-none"></div>

      <div class="relative space-y-5">
        <!-- Category badge -->
        <div class="flex items-center gap-3 flex-wrap">
          {#if featured}
            <span class="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-700/40">
              <span class="i-lucide-star text-xs"></span>
              Featured
            </span>
          {/if}
          <span class="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full bg-gradient-to-r {catGradient} text-white shadow-sm">
            <span class="i-lucide-layers text-xs"></span>
            {category}
          </span>
        </div>

        <!-- Title -->
        <h1 class="text-3xl sm:text-4xl md:text-5xl font-extrabold leading-tight text-slate-900 dark:text-white">
          {title}
        </h1>

        <p class="text-lg md:text-xl text-slate-600 dark:text-slate-300 max-w-3xl leading-relaxed">
          {description}
        </p>

        <!-- Meta row -->
        <div class="flex flex-wrap gap-4 pt-2 text-sm text-slate-500 dark:text-slate-400">
          {#if formattedDate}
            <span class="inline-flex items-center gap-1.5">
              <span class="i-lucide-calendar text-base"></span>
              {formattedDate}
            </span>
          {/if}
          {#if duration}
            <span class="inline-flex items-center gap-1.5">
              <span class="i-lucide-clock text-base"></span>
              {duration}
            </span>
          {/if}
          {#if role}
            <span class="inline-flex items-center gap-1.5">
              <span class="i-lucide-user text-base"></span>
              {role}
            </span>
          {/if}
          <span class="inline-flex items-center gap-1.5">
            <span class="i-lucide-book-open text-base"></span>
            {readTime} min read
          </span>
        </div>

        <!-- Tags -->
        {#if tags.length > 0}
          <div class="flex flex-wrap gap-2 pt-1">
            {#each tags as tag}
              <a
                href="/case-studies?tag={encodeURIComponent(tag)}"
                class="skill-tag text-xs no-underline"
              >
                <span class="i-lucide-tag text-xs mr-0.5"></span>
                {tag}
              </a>
            {/each}
          </div>
        {/if}
      </div>
    </div>

    <!-- Tech Stack -->
    {#if stack.length > 0}
      <div class="mt-5 glass-card p-4 sm:p-5">
        <div class="flex items-center gap-3 flex-wrap">
          <span class="text-xs font-semibold uppercase tracking-widest text-slate-400 dark:text-slate-500 shrink-0">Stack</span>
          <div class="flex flex-wrap gap-2">
            {#each stack as tech}
              <span class="inline-flex items-center gap-1 text-xs font-medium px-2.5 py-1 rounded-md bg-slate-100 dark:bg-slate-700/60 text-slate-700 dark:text-slate-300 border border-slate-200/60 dark:border-slate-600/40">
                {tech}
              </span>
            {/each}
          </div>
        </div>
      </div>
    {/if}
  </header>

  <!-- Article Content — MDSveX renders the markdown here -->
  <article class="project-prose">
    <slot />
  </article>

  <!-- Footer CTA -->
  <div class="mt-16 pt-10 border-t border-slate-200/40 dark:border-slate-700/30 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
    <a
      href="/case-studies"
      class="inline-flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400 hover:text-primary-600 dark:hover:text-primary-400 transition-colors no-underline group"
    >
      <span class="i-lucide-arrow-left text-base group-hover:-translate-x-0.5 transition-transform"></span>
      {sections.back_to_case_studies || "Back to All Case Studies"}
    </a>
    <a
      href="/"
      class="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-primary-500 to-primary-600 text-white px-5 py-2.5 text-sm font-semibold shadow-md hover:shadow-lg hover:shadow-primary-500/20 transition-all duration-300 hover:-translate-y-0.5 no-underline"
    >
      {sections.view_portfolio || "View Full Portfolio"}
      <span class="i-lucide-arrow-right text-base"></span>
    </a>
  </div>
</div>

<style>
  /* ─── Prose typography for MDSveX rendered content ─── */
  :global(.project-prose) {
    max-width: 80ch;
    margin: 0 auto;
    color: #334155;
  }
  :global(html.dark .project-prose) {
    color: #cbd5e1;
  }
  :global(.project-prose h2) {
    font-size: 1.6rem;
    font-weight: 800;
    margin-top: 2.5rem;
    margin-bottom: 1rem;
    color: #0f172a;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid rgba(20,184,166,0.2);
  }
  :global(html.dark .project-prose h2) {
    color: #f1f5f9;
    border-bottom-color: rgba(20,184,166,0.15);
  }
  :global(.project-prose h3) {
    font-size: 1.2rem;
    font-weight: 700;
    margin-top: 1.8rem;
    margin-bottom: 0.75rem;
    color: #0f172a;
  }
  :global(html.dark .project-prose h3) { color: #f1f5f9; }
  :global(.project-prose h4) {
    font-size: 1rem;
    font-weight: 700;
    margin-top: 1.5rem;
    margin-bottom: 0.5rem;
    color: #1e293b;
  }
  :global(html.dark .project-prose h4) { color: #e2e8f0; }
  :global(.project-prose p) {
    line-height: 1.85;
    margin-bottom: 1.1rem;
  }
  :global(.project-prose ul),
  :global(.project-prose ol) {
    padding-left: 1.5rem;
    margin-bottom: 1.1rem;
    display: flex;
    flex-direction: column;
    gap: 0.4rem;
  }
  :global(.project-prose li) { line-height: 1.75; }
  :global(.project-prose ul > li) { list-style: disc; }
  :global(.project-prose ol > li) { list-style: decimal; }
  :global(.project-prose ul > li::marker) { color: #14b8a6; }
  :global(.project-prose ol > li::marker) { color: #14b8a6; }
  :global(.project-prose strong) { color: #0f172a; font-weight: 700; }
  :global(html.dark .project-prose strong) { color: #f1f5f9; }
  :global(.project-prose code:not(pre code)) {
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.82em;
    padding: 0.15em 0.45em;
    border-radius: 5px;
    background: rgba(20,184,166,0.08);
    color: #0d9488;
    border: 1px solid rgba(20,184,166,0.2);
  }
  :global(html.dark .project-prose code:not(pre code)) {
    background: rgba(20,184,166,0.1);
    color: #5eead4;
    border-color: rgba(20,184,166,0.15);
  }
  /* ─── Shiki code blocks ─── */
  :global(.shiki-container) {
    margin: 1.5rem 0;
    border-radius: 1rem;
    overflow: hidden;
    border: 1px solid rgba(226,232,240,0.5);
    box-shadow: 0 4px 24px -4px rgba(0,0,0,0.1);
  }
  :global(html.dark .shiki-container) {
    border-color: rgba(51,65,85,0.4);
  }
  :global(.shiki-container pre) {
    padding: 1.25rem 1.5rem;
    overflow-x: auto;
    font-size: 0.88rem;
    line-height: 1.7;
    margin: 0;
    border-radius: 0;
  }
  /* Show light/dark shiki themes based on html class */
  :global(.shiki-container .shiki.github-light) { display: block; }
  :global(.shiki-container .shiki.github-dark) { display: none; }
  :global(html.dark .shiki-container .shiki.github-light) { display: none; }
  :global(html.dark .shiki-container .shiki.github-dark) { display: block; }
  /* ─── Mermaid diagrams ─── */
  :global(.project-prose .mermaid-wrapper) {
    margin: 1.5rem 0;
    padding: 1.5rem;
    border-radius: 1rem;
    background: #f8fafc;
    border: 1px solid rgba(226,232,240,0.8);
    overflow-x: auto;
    text-align: center;
  }
  :global(html.dark .project-prose .mermaid-wrapper) {
    background: rgba(15,23,42,0.6);
    border-color: rgba(51,65,85,0.5);
  }
  /* ─── Blockquotes ─── */
  :global(.project-prose blockquote) {
    border-left: 4px solid #14b8a6;
    padding: 0.75rem 1.25rem;
    margin: 1.5rem 0;
    background: rgba(20,184,166,0.04);
    border-radius: 0 0.75rem 0.75rem 0;
    color: #475569;
    font-style: italic;
  }
  :global(html.dark .project-prose blockquote) {
    background: rgba(20,184,166,0.06);
    color: #94a3b8;
  }
  /* ─── Tables ─── */
  :global(.project-prose table) {
    width: 100%;
    border-collapse: collapse;
    margin: 1.5rem 0;
    font-size: 0.9rem;
  }
  :global(.project-prose th) {
    padding: 0.6rem 1rem;
    background: rgba(20,184,166,0.08);
    font-weight: 700;
    text-align: left;
    border-bottom: 2px solid rgba(20,184,166,0.25);
  }
  :global(.project-prose td) {
    padding: 0.6rem 1rem;
    border-bottom: 1px solid rgba(226,232,240,0.6);
  }
  :global(html.dark .project-prose th) {
    background: rgba(20,184,166,0.07);
    border-bottom-color: rgba(20,184,166,0.2);
  }
  :global(html.dark .project-prose td) {
    border-bottom-color: rgba(51,65,85,0.4);
  }
  /* ─── Horizontal rules ─── */
  :global(.project-prose hr) {
    border: none;
    border-top: 1px solid rgba(226,232,240,0.5);
    margin: 2rem 0;
  }
  :global(html.dark .project-prose hr) {
    border-top-color: rgba(51,65,85,0.4);
  }
</style>
